### ISSUE TITLE
About CORD-Lv1

### ISSUE THREAD

**Issue by saichandrapandraju** [zlwang-cs/LASER-release#3]
Hi @zlwang-cs ,

Thanks for the great work on Few-shot Entity Recognition.

This repo contains only FUNSD data and shell script. As CORD-Lv1 is also presented in the paper, could you provide steps to evaluate this framework on CORD-Lv1..?

**Comment by zlwang-cs** [comment]
Thanks for your interests in our work. The CORD-lv1 is processed and evaluated in the same way as FUNSD.

**Comment by zlwang-cs** [comment]
I updated the instructions. Hope this will help you run the experiments.
